HUB-457
marfatech/rabbit-queue-bundle pull request #10
Opened 2022-09-02 14:23 UTC by NazarenkoIvan

2022-09-02 16:40 UTC, iskripka commented on Client/RabbitMqClient.php
> +    protected function channelPublishPool(array $messageList, int $retriesCount = 0): void
Добавить аннотации типа параметра массива $messageList
QueuePoolMessage[]

2022-09-02 16:49 UTC, iskripka commented on DependencyInjection/Configuration.php
> +                ->integerNode('reconnect_retries')
Закинуть в options, там как раз ему место

2022-09-05 08:30 UTC, iskripka commented on Client/RabbitMqClient.php
> +            if ($retriesCount < $this->reconnectRetries) {
Если 3 попытки пройдет будет тихое падение и кроме логов мы не узнаем?

2022-09-05 09:33 UTC, NazarenkoIvan commented on Client/RabbitMqClient.php
> +            if ($retriesCount < $this->reconnectRetries) {
получается так
выбрасывать исключение в таком случае?

2022-09-12 07:36 UTC, iskripka commented
Добавить запись о реконнекте и новом параметре reconnectRetries в changelog

2022-09-13 09:12 UTC, revilon1991 requested changes
- [ ] Написать тест на новый параметр
- [ ] Добавить инфу о новом параметре в [README.md](https://github.com/marfatech/rabbit-queue-bundle/blob/master/README.md)

2022-09-29 09:41 UTC, revilon1991 approved these changes

2022-09-29 09:42 UTC, merged