HUB-416 added ability to send additional properties with message
marfatech/rabbit-queue-bundle pull request #3
Opened 2021-09-30 15:36 UTC by iskripka

2021-09-30 16:46 UTC, revilon1991 approved these changes

2021-10-01 11:02 UTC, avirskiywakeapp requested changes

2021-10-01 11:12 UTC, avirskiywakeapp commented on Tests/Producer/RabbitMqProducerTest.php
> +        $this->producer->put(QueueEnum::EXAMPLE_FIFO, self::TEST_MESSAGE, self::TEST_OPTIONS, null, self::TEST_PARAMS);
Не туда написал - это к тестам паблишеров.
Создание колбэк-объекта можно в абстрактный тест кейс вынести статиком с поздним связыванием.

2021-10-01 11:38 UTC, iskripka commented on Producer/RabbitMqProducerInterface.php
> +        ?string $routingKey = null,
В принципе таких мест нет, просто более нативно будет, если null - то не задан вообще роутинг кей, соответственно не будет проверок на пустую строку типа $routingKey !== ''

2021-10-01 14:04 UTC, avirskiywakeapp approved these changes

2021-10-01 14:23 UTC, merged