HUB-432
marfatech/rabbit-queue-bundle pull request #5
Opened 2022-05-05 15:06 UTC by atotskii

2022-05-05 16:48 UTC, iskripka commented on README.md
> +        batch_timeout: 10                 # таймаут сборки партии сообщений в секундах (по умолчанию 10)
Лучше поставить 0, чтоб не ломать обратную совместимость, иначе не будет добираться пачка например на памятках, там 15к пачка

2022-05-05 21:38 UTC, iskripka commented on Command/ConsumerRunCommand.php
>                      $this->batchConsume($consumer, $messageList);
Такая ситуация: 
получили 1 сообщение в messageList и на `$this->client->wait($timeout);` падаем, так как задан wait_timeout
попадаем в catch и обрабатываем. Таймаут у нас перекидывается на следующую пачку и мы законцим ее раньше времени batch_timeout

Нужно здесь обнулять тоже `$batchTime = 0;`

2022-05-06 09:40 UTC, atotskii commented on Command/ConsumerRunCommand.php
>                      $this->batchConsume($consumer, $messageList);
Добавил проперти float $batchTime и перенес $this->batchTime = 0 в batchConsume();

2022-05-11 13:07 UTC, iskripka commented on Command/ConsumerRunCommand.php
> +            if (count($messageList) === $batchSize || $this->batchTime >= $this->getBatchTimeout()) {
В таком случае будем по одному сообщению обрабатывать, если таймаут 0 по дефолту 
`$this->batchTime >= $this->getBatchTimeout()` => `0 >= 0 true`

2022-05-12 08:28 UTC, iskripka approved these changes

2022-05-13 10:22 UTC, revilon1991 requested changes

2022-05-13 10:22 UTC, revilon1991 commented on Command/ConsumerRunCommand.php
> +                count($messageList) === $batchSize ||
- [ ] вынести условия за скобки, чтобы не было переносов в if
```php
$isBatchAccumulated = count($messageList) === $batchSize;
$isBatchTimeout = $this->getBatchTimeout() > 0 && $this->batchTime >= $this->getBatchTimeout();

if ($isBatchAccumulated || $isBatchTimeout) {
    // ...
}
```

2022-05-13 10:22 UTC, revilon1991 commented on Command/ConsumerRunCommand.php
> +            $timeStart = microtime(true);
- [ ] вместо `microtime` можно использовать `time`, чтобы уйти от `float`, в конфиге можно задавать только в секундах

2022-05-13 10:22 UTC, revilon1991 commented on Command/ConsumerRunCommand.php
> +                $this->batchTime += microtime(true) - $timeStart;
- [ ] вместо свойства объекта использовать переменную, занулять ее в двух местах после `batchConsume` не выглядит проблемой.

2022-05-13 14:55 UTC, atotskii commented on Command/ConsumerRunCommand.php
> +            $timeStart = microtime(true);
Если задать batch_timeout = 1 сек (он такой на aramuz и будет), то никогда не попадет в условие, если будут хандлеры < 1 сек выполняться, $batchTime будет всегда = 0

2022-05-13 16:23 UTC, revilon1991 commented on Command/ConsumerRunCommand.php
> +            $timeStart = microtime(true);
В теории можно словить другой баг, если wait клиента будет отрабатывать меньше чем 1 секунда, тогда обработка не запустится в текущую итерацию.

Предлагаю юзать микросекунды в таком виде и хранить их как `int`
```php
$timeStart = (int) (new DateTime())->format('Uu');
```

2022-05-16 08:04 UTC, revilon1991 approved these changes

2022-05-16 10:26 UTC, revilon1991 approved these changes

2022-05-16 10:26 UTC, merged