HUB-442 support of multiple connections
marfatech/rabbit-queue-bundle pull request #7
Opened 2022-06-20 09:13 UTC by apogadaev

2022-06-21 09:22 UTC, iskripka approved these changes

2022-06-21 09:44 UTC, iskripka approved these changes

2022-06-22 11:05 UTC, revilon1991 commented on DependencyInjection/Configuration.php
> +                ->arrayNode('hosts')
- [ ] оставить прежнее название

2022-06-22 11:06 UTC, revilon1991 commented on DependencyInjection/Configuration.php
> -                            ->integerNode('connection_timeout')->defaultValue(3)->end()
- [ ] не удалять опции, читать из первого коннекта настрйоки и использовать их для нового ключа `options`
старые же опции задепрекейтить и тексте указать почему устарело и как использовать по новой схеме эти настройки

2022-06-22 11:07 UTC, revilon1991 commented on Factory/ConnectionFactory.php
> +declare(strict_types=1);
указать авторские права, см другие публичные бандлы

2022-06-22 11:07 UTC, revilon1991 commented on README.md
> +    hosts:                                # список хостов для подключения
- [ ] актуализировать опции на основе конфигурации

2022-06-22 11:08 UTC, revilon1991 commented on README.md
> +Подключение будет происходить для нескольких хостов. [Multiple hosts connections](https://github.com/php-amqplib/php-amqplib#multiple-hosts-connections)
- [ ] текст другой, суть в том, что будет создан первый попавшийся, а не несколько

2022-06-23 09:34 UTC, revilon1991 requested changes

2022-06-23 09:34 UTC, revilon1991 commented on CHANGELOG.md
> +- Сopyrights are indicated.
- [ ] это не несет ценности для читателя

2022-06-23 09:34 UTC, revilon1991 commented on DependencyInjection/Configuration.php
> +                        ->integerNode('connection_timeout')->defaultValue(3)->end()
значения по умолчанию для этих опций точно проставляются, если их не указать в конфиге?

2022-06-23 09:34 UTC, revilon1991 commented on DependencyInjection/Configuration.php
> +    private function getDeprecationMsg(string $message, string $version): array
- [ ] `msg` => `message`

2022-06-23 09:34 UTC, revilon1991 commented on DependencyInjection/Configuration.php
> +        if (method_exists(BaseNode::class, 'getDeprecation')) {
- [ ] ориентироваться на версию симфони, а не наличие метода, это лучше объясняет зачем такие условности были сделаны.
---
`$message` - для версий ниже чем 5.1
`$package, $version, $message` - для всех остальных

2022-06-23 09:34 UTC, revilon1991 commented on README.md
> +Попытка подключения к хостам, указанных в ключа конфигурации `connection`, будет происходить по очереди и вернет первое удачное подключение. [Multiple hosts connections](https://github.com/php-amqpli
```suggestion
Попытка подключения к хостам, указанных в ключе конфигурации `connection`, будет происходить по очереди и вернет первое удачное подключение. [Multiple hosts connections](https://github.com/php-amqplib/php-amqplib#multiple-hosts-connections) 
```

2022-06-23 09:43 UTC, apogadaev commented on DependencyInjection/Configuration.php
> +                        ->integerNode('connection_timeout')->defaultValue(3)->end()
1. 
![image](https://user-images.githubusercontent.com/76207138/175268929-3de0e01a-4a82-4c38-9ae1-50f4c675204c.png)
проставляются
<img width="727" alt="image" src="https://user-images.githubusercontent.com/76207138/175269091-0763125d-60db-491a-895f-95dc2f065aca.png">

2.
![image](https://user-images.githubusercontent.com/76207138/175269384-d53b9765-8dec-4d90-8ba4-10bb37abb2e5.png)
не проставляются
<img width="454" alt="image" src="https://user-images.githubusercontent.com/76207138/175269521-2cb3011d-f0a2-496f-b937-42e85d2f6eb4.png">

2022-06-23 12:01 UTC, apogadaev commented on DependencyInjection/Configuration.php
> +            ];
метод `InstalledVersions::getRootPackage()`
возвращает некорректное имя бандла:

<img width="474" alt="image" src="https://user-images.githubusercontent.com/76207138/175291675-0eca68f4-a6a2-44ca-97af-b3c59702823a.png">

предлагаю использовать следующее решение
```php
return [
    'marfatech/rabbit-queue-bundle',
    InstalledVersions::getVersion('marfatech/rabbit-queue-bundle'),
    $message,
];
```

2022-06-24 15:47 UTC, revilon1991 approved these changes

2022-06-24 15:53 UTC, merged